# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OAuthQQUser',
            new_name='QQAuthUser',
        ),
    ]
